In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pickle 

In [2]:
def get_model_from_ID(ID):
  return df[df.ID == ID]["model"].values[0]

def get_ID_from_model(model):
  return df[df.model == model]["ID"].values[0]

In [3]:
df = pd.read_csv(r"C:\Users\conor\Documents\phone_recommendation\mobil_phone_rating.csv")

In [4]:
features = ['price', 'camera', 'display', 'battery']

for feature in features:
  df[feature] = df[feature].fillna('')

In [5]:
def combined_features(row):
  combined_features = pd.DataFrame(df, columns= ['price','camera','display','battery'])

df["combined_features"] = df['price'].map(str) + ',' + df['camera'].map(str) + ',' + df['display'].map(str) + ',' + df['battery'].map(str)


In [6]:
df

ID                    model  price  launch  camera  selfie  audio  \
0      1           Huawei P50 Pro   $907  Jul-21     144   106.0    NaN   
1      2       Xiaomi Mi 11 Ultra  $1200  Mar-21     143    94.0   71.0   
2      3      Huawei Mate 40 Pro+  $1363  Oct-20     139     NaN    NaN   
3      4  Apple iPhone 13 Pro Max  $1099  Sep-21     137    99.0   75.0   
4      5      Apple iPhone 13 Pro   $999  Sep-21     137    99.0   75.0   
..   ...                      ...    ...     ...     ...     ...    ...   
218  219          Huawei P40 Lite   $279  Feb-20      39     NaN    NaN   
219  220           Wiko Power U20   $159  Jan-21      39     NaN    NaN   
220  221   Motorola Moto G9 Power   $229  Nov-20      37     NaN    NaN   
221  222               Realme C11   $119  Jun-20      37     NaN    NaN   
222  223           Xiaomi Redmi 9   $159  Jun-20      37     NaN    NaN   

     display  battery combined_features  
0         93       81    $907,144,93,81  
1         87       69   $1200,143,87,69  
2         85       89   $1363,139,85,89  
3         99       89   $1099,137,99,89  
4         98       76    $999,137,98,76  
..       ...      ...               ...  
218       41       73     $279,39,41,73  
219       38       70     $159,39,38,70  
220       35       70     $229,37,35,70  
221       30       61     $119,37,30,61  
222       25       54     $159,37,25,54  

[223 rows x 10 columns]

In [7]:
cv = CountVectorizer()

count_matrix = cv.fit_transform(df["combined_features"])

print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
cosine_sim = cosine_similarity(count_matrix)
cosine_sim

array([[1.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , ..., 0.  , 0.  , 0.  ],
       ...,
       [0.  , 0.  , 0.  , ..., 1.  , 0.25, 0.25],
       [0.  , 0.  , 0.  , ..., 0.25, 1.  , 0.25],
       [0.  , 0.  , 0.  , ..., 0.25, 0.25, 1.  ]])

In [9]:
user_current_phone = "Google Pixel 4"

phone_ID = get_ID_from_model(user_current_phone)

similar_phones = list(enumerate(cosine_sim[phone_ID]))
sorted_similar_phones = sorted(similar_phones,key=lambda x:x[1],reverse=True)

In [10]:
def index():
 i = 0
 for phone in sorted_similar_phones:
    print (get_model_from_ID(phone[0]))
    i=i+1
    if i > 3:
      break

In [11]:
index()

Google Pixel 4
Honor 20 Pro
Huawei Mate 20 X
Xiaomi Mi 8


In [12]:
import pickle

In [13]:
pickle.dump(df,open("meta_data.pkl","wb"))
pickle.dump(cosine_sim,open("simiarity.pkl","wb"))

In [14]:
np.array(df["model"])

array(['Huawei P50 Pro', 'Xiaomi Mi 11 Ultra', 'Huawei Mate 40 Pro+',
       'Apple iPhone 13 Pro Max', 'Apple iPhone 13 Pro',
       'Huawei Mate 40 Pro', 'Google Pixel 6 Pro', 'Vivo X70 Pro+',
       'Asus Smartphone for Snapdragon Insiders', 'Xiaomi Mi 10 Ultra',
       'Google Pixel 6', 'Huawei P40 Pro', 'Oppo Find X3 Pro',
       'Vivo X70 Pro (MediaTek)', 'Vivo X50 Pro+', 'Apple iPhone 13',
       'Apple iPhone 13 mini', 'Apple iPhone 12 Pro Max',
       'Apple iPhone 12 Pro', 'Vivo X60 Pro+', 'Xiaomi Mi 10 Pro',
       'Oppo Find X2 Pro', 'Samsung Galaxy S20 Ultra 5G (Exynos)',
       'Honor 30 Pro+', 'Apple iPhone 11 Pro Max', 'OnePlus 9 Pro',
       'Samsung Galaxy Z Fold3 5G', 'Huawei Mate 30 Pro 5G',
       'Samsung Galaxy S21 Ultra 5G (Snapdragon)', 'Apple iPhone 12 mini',
       'Apple iPhone 12', 'Honor V30 Pro', 'Huawei Mate 30 Pro',
       'Oppo Reno6 Pro 5G', 'Oppo Reno6 Pro+',
       'Samsung Galaxy S21 Ultra 5G (Exynos)',
       'Xiaomi Mi CC9 Pro Premium Edition', '